# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-terragrunt-states"
    dynamodb_table = "terraform_lock_db"
    encrypt        = false
    key            = "dev/kms_key/terraform.tfvars"
    profile        = "default"
    region         = "us-east-1"
  }
}
